### ISSUE TITLE
Thanks for this. Is this a maintained fork?

### ISSUE THREAD

**Issue by Rush** [gmt2001/ouroboros#32]
Hi -  I noticed your fix to the issue I was suffering from in this PR https://github.com/pyouroboros/ouroboros/pull/395

THANK YOU! I am yet to test it but it's great to see a maintained fork.

Do you plan to support it on an ongoing basis?

**Comment by gmt2001** [comment]
If something comes up, I'll try to resolve it.

My other issues are future ideas that I am unsure when I would work on.
