### ISSUE TITLE
SyntaxError: invalid syntax. Perhaps you forgot a comma?

### ISSUE THREAD

**Issue by azumukupoe** [gmt2001/ouroboros#44]
```
ouroboros    | SyntaxError: invalid syntax. Perhaps you forgot a comma?

ouroboros    | Traceback (most recent call last):

ouroboros    |   File "/usr/local/bin/ouroboros", line 2, in <module>

ouroboros    |     from pyouroboros.ouroboros import main

ouroboros    |   File "/usr/local/lib/python3.10/site-packages/pyouroboros/ouroboros.py", line 105

ouroboros    |     docker_group.add_argument('-L', '--latest-only', default=Config.latest_only dest='LATEST_ONLY', action='store_true',
```

**Comment by azumukupoe** [comment]
I've tried the latest release but am still getting the same error
```
ouroboros    | SyntaxError: invalid syntax. Perhaps you forgot a comma?

ouroboros    | Traceback (most recent call last):

ouroboros    |   File "/usr/local/bin/ouroboros", line 2, in <module>

ouroboros    |     from pyouroboros.ouroboros import main

ouroboros    |   File "/usr/local/lib/python3.10/site-packages/pyouroboros/ouroboros.py", line 105

ouroboros    |     docker_group.add_argument('-L', '--latest-only', default=Config.latest_only dest='LATEST_ONLY', action='store_true',
```

**Comment by gmt2001** [comment]
It looks like your Docker hasn't pulled the image

If you used docker-compose:
1. `cd` into the directory with the `docker-compose.yml` file
2. `docker-compose pull`
3. `docker-compose up -d --remove-orphans`
4. `docker image prune`


If you used `docker run`:
1. Delete the ouroboros container
2. Run `docker pull gmt2001/ouroboros:latest` (Docker Hub) or `docker pull ghcr.io/gmt2001/ouroboros:latest` (GitHub Container Registry)
3. Create a new ouroboros container

**Comment by azumukupoe** [comment]
> It looks like your Docker hasn't pulled the image
> 
> If you used docker-compose:
> 
>     1. `cd` into the directory with the `docker-compose.yml` file
> 
>     2. `docker-compose pull`
> 
>     3. `docker-compose up -d --remove-orphans`
> 
>     4. `docker image prune`
> 
> 
> If you used `docker run`:
> 
>     1. Delete the ouroboros container
> 
>     2. Run `docker pull gmt2001/ouroboros:latest` (Docker Hub) or `docker pull ghcr.io/gmt2001/ouroboros:latest` (GitHub Container Registry)
> 
>     3. Create a new ouroboros container
> 
>     4. `docker image prune`

you were right
how could I forget that? 🤣
