### ISSUE TITLE
'/app/pyouroboros/hooks' does not exists

### ISSUE THREAD

**Issue by Qhilm** [gmt2001/ouroboros#77]
I get this error when trying to deploy using the [docker compose file](https://github.com/gmt2001/ouroboros/blob/main/docker-compose.yml).

This is on DSM 7, docker 20.10.

**Comment by gmt2001** [comment]
It is trying to find that folder on your server

You can create the folder on your server or, if you do not want to use the hooks feature, you can remove the last line of the Docker Compose file

**Comment by Qhilm** [comment]
ah yes, that was obvious, I misread it and thought a folder was missing in the container...
